#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

setxkbmap fr,ar, azerty -model pc10 -option grp:alt_shift_toggle&

/home/salah/.config/polybar/material/launch.sh

#bspc monitor -d I II III IV V VI VII VIII IX X
bspc monitor -d 0 1 2 3 4 5 6 7 8 9


bspc config border_width         
bspc config window_gap		 5

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true

bspc config single_monocle true
#bspc config gapless_monocle true

bspc config border_radius 10


bspc config top_padding 49
bspc config left_padding 0
bspc config right_padding 0
bspc config bottom_padding 49



bspc config normal_border_color "#44475a"
#bspc config active_border_color "#bd93f9"
#bspc config focused_border_color "#ff79c6"
bspc config presel_feedback_color "#6272a4"

bspc config active_border_color "#ffb300"
bspc config focused_border_color "#ffb300"


bspc rule -a Gimp desktop='^8' state=floating follow=on rectangle=1280x990+0+35
bspc rule -a "Gimp-2.10" desktop='^8' state=floating follow=on rectangle=1280x990+0+35
bspc rule -a firefox desktop='^2'
bspc rule -a Spotify desktop='^7'
bspc rule -a mplayer2 state=floating
bspc rule -a Kupfer.py focus=on
bspc rule -a Screenkey manage=off
bspc rule -a subl desktop='^4'
bspc rule -a discord desktop='^6'
bspc rule -a copyq state=floating
bspc rule -a firefox:Toolkit sticky=on state=floating
bspc rule -a Ristretto state=floating rectangle=1280x990+0+35
bspc rule -a OpenBoard state=floating



picom --experimental-backends --backend glx  &
dunst -conf ~/.config/dunst/dunstrc &
copyq &

#redshift -r

status=`pidof redshift | wc -l`
if [[ "$status" != 1 ]]; then
    	redshift -r
fi
